"use strict";(function(n){window.initializeTTSDemo=function(t){n(document).ready(function(){function ot(){var i=s.SpeechTranslationConfig.fromAuthorizationToken(t.token,
t.region),
n,
r;i.speechSynthesisOutputFormat=s.SpeechSynthesisOutputFormat.Audio24Khz160KBitRateMonoMp3;a=new s.SpeakerAudioDestination;a.onAudioEnd=function(){y.hidden=!0;v.hidden=!1};r=s.AudioConfig.fromSpeakerOutput(a);n=new s.SpeechSynthesizer(i,     
r);n.synthesisCompleted=function(){n.close();n=null};n.SynthesisCanceled=function(n,
i){var r;y.hidden=!0;v.hidden=!1;r=s.CancellationDetails.fromResult(i);r.reason===s.CancellationReason.Error&&(w.innerText=t.srTryAgain)};n.speakSsmlAsync(it.value,
function(){},
function(n){w.innerText=t.srTryAgain+" "+n})}function h(){var n='<prosody rate="{SPEED}" pitch="{PITCH}">{TEXT}<\/prosody>',
t;n=n.replace("{SPEED}",
f.value+"%");n=n.replace("{PITCH}",
e.value+"%");u.selectedIndex===0&&(p.hidden||o.selectedIndex===0)||(n="<mstts:express-as {STYLE_ATTRIBUTE} {ROLE_PLAY_ATTRIBUTE}>{0}<\/mstts:express-as>".replace("{0}",
n),
n=u.selectedIndex!==0?n.replace("{STYLE_ATTRIBUTE}",
'style="'+u[u.selectedIndex].value+'"'):n.replace("{STYLE_ATTRIBUTE}",
""),
n=p.hidden||o.selectedIndex===0?n.replace("{ROLE_PLAY_ATTRIBUTE}",
""):n.replace("{ROLE_PLAY_ATTRIBUTE}",
'role="'+o[o.selectedIndex].value+'"'));n='<voice name="{VOICE}">{0}<\/voice>'.replace("{0}",
n);n=n.replace("{VOICE}",
i[i.selectedIndex].value);t=d.value.replace(/&/g,
"&amp;").replace(/</g,
"&lt;").replace(/>/g,
"&gt;").replace(/"/g,
"&quot;").replace(/'/g,
"&apos;");k.hidden||(t='<lang xml:lang="{SECONDARY_LOCALE}">{0}<\/lang>'.replace("{0}",
t),
t=t.replace("{SECONDARY_LOCALE}",
c[c.selectedIndex].value));n='<speak xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xmlns:emo="http://www.w3.org/2009/10/emotionml" version="1.0" xml:lang="en-US">{0}<\/speak>'.replace("{0}",
n);n=n.replace("{TEXT}",
t);it.value=n}var rt=document.getElementById("playbtn"),
v=document.getElementById("playli"),
ut=document.getElementById("stopbtn"),
y=document.getElementById("stopli"),
r=document.getElementById("languageselect"),
i=document.getElementById("voiceselect"),
u=document.getElementById("voicestyleselect"),
o=document.getElementById("roleplayselect"),
p=document.getElementById("roleplayselectdiv"),
c=document.getElementById("secondarylocaleselect"),
k=document.getElementById("secondarylocaleselectdiv"),
d=document.getElementById("ttstext"),
it=document.getElementById("ttsssml"),
w=document.getElementById("ttsstatus"),
f=document.getElementById("speed"),
ft=document.getElementById("speedlabel"),
e=document.getElementById("pitch"),
et=document.getElementById("pitchlabel"),
a=null,
s=window.SpeechSDK,
b={},
g={},
nt={},
tt={},
l;s=window.SpeechSDK;n.ajax({url:"https://"+t.region+".tts.speech.microsoft.com/cognitiveservices/voices/list",
type:"GET",
beforeSend:function(n){n.setRequestHeader("Authorization",
"Bearer "+t.token)},
success:function(i){var u=i.sort(function(n,
t){return n.VoiceType.localeCompare(t.VoiceType)});n.each(u,
function(n,
i){var r=i.DisplayName;b[i.Locale]||(b[i.Locale]="");i.VoiceType==="Neural"&&(r+=" (Neural)");i.LocalName!==i.DisplayName&&(r+=" - "+i.LocalName);i.Status==="Preview"&&(r+=" - "+t.ttsPreview);b[i.Locale]+='<option value="'+i.ShortName+'">'+r+"<\/option>";g[i.ShortName]=i.StyleList;nt[i.ShortName]=i.RolePlayList;tt[i.ShortName]=i.SecondaryLocaleList});r.onchange()},
error:function(n,
i,
r){w.innerText=t.srTryAgain;global.Core.Util.TrackException("A Text To Speech voice list API Ajax error occurred: "+r)}});ut.onclick=function(){v.hidden=!1;y.hidden=!0;a!==null&&a.pause();a=null};

rt.onclick=function(){
    y.hidden=!1;
    v.hidden=!0;
    w.innerText="";
    ot(function(){})
};
    r.onchange=function(){l="";
    n.each(t.ttsDefaultText, function(n,t){r[r.selectedIndex].value===n?l=t:!l&&r[r.selectedIndex].value.startsWith(n)&&(l=t)});l||(l=t.ttsDefaultText.default);
    
    d.value=l;
    i.innerHTML=b[r[r.selectedIndex].value];
    i.onchange();h()};
    i.onchange=function(){u.innerHTML="";
    u.options.add(new Option("General","general"));
    g[i[i.selectedIndex].value]?(n.each(g[i[i.selectedIndex].value],
        function(n,t){u.options.add(new Option((t[0].toUpperCase()+t.slice(1)).replace("Customerservice","Customer Service").replace("Voiceassistant","Voice Assistant"),t))}),
u.disabled=!1):u.disabled=!0;nt[i[i.selectedIndex].value]?(o.innerHTML="",
o.options.add(new Option("Default",
"Default")),
n.each(nt[i[i.selectedIndex].value],
function(n,
t){o.options.add(new Option(t,
t))}),
p.hidden=!1):p.hidden=!0;tt[i[i.selectedIndex].value]?(c.innerHTML="",
c.options.add(new Option(r[r.selectedIndex].text+" - Default",
r[r.selectedIndex].value)),
n(r.options).each(function(){tt[i[i.selectedIndex].value].includes(n(this).attr("value"))&&c.options.add(new Option(n(this).text(),
n(this).attr("value")))}),
k.hidden=!1):k.hidden=!0;e.disabled=!1;f.disabled=!1;h()};u.onchange=function(){h()};o.onchange=function(){h()};c.onchange=function(){c.selectedIndex!==0?(e.disabled=!0,
f.disabled=!0):(e.disabled=!1,
f.disabled=!1);h()};e.oninput=function(){var n=(e.value-e.min)/(e.max-e.min)*2,
i;i=Math.abs(n)<1?n.toPrecision(2):n.toPrecision(3);et.innerText=t.ttsPitch+": "+i};e.onchange=function(){h()};f.oninput=function(){var n=(f.value-f.min)/(f.max-f.min)*3,
i;i=Math.abs(n)<1?n.toPrecision(2):n.toPrecision(3);ft.innerText=t.ttsSpeed+": "+i};f.onchange=function(){h()};d.onchange=function(){h()}})}})(jQuery)